repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: ["--profile", "black", "--filter-files", "--check", "etl"]

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -    id: black
         files: ^etl/
         args: ['--config=pyproject.toml', '--check', 'etl']

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        files: ^etl/

-   repo: https://github.com/PyCQA/pylint
    rev: v3.1.0

    hooks:
    -   id: pylint
        files: ^etl/
        args:
          [
            '--reports=no',
            'etl',
            '--rcfile=.pylintrc',
          ]
