project:
  type: book

book:
  title: |
    DAVICU-1 Mapping Document Source Data Mapping Approach to CDMV5.4.1
  subtitle: |
    INCEPT data science team in collaboration with edenceHealth NV
  author: "Benjamin Skov Kaas-Hansen, Davide Placido"
  date: now
  date-format: DD MMMM YYYY
  search: true
  chapters:
    - part: "Background"
      chapters:
        - index.qmd
        - technical_infrastructure.qmd
    - part: "Mapping"
      chapters:
        - mapping_overview.qmd
        - site_etl.qmd
        - merge_etl.qmd
        - vocabularies.qmd
    - part: "Mapped OMOP tables"
      chapters:
        - health_system_data_tables.qmd
        - clinical_data_tables.qmd
        - standardized_derived_elements.qmd
        - metadata_tables.qmd
  appendices:
    - appendix_A.qmd
    - appendix_B.qmd
    - appendix_C.qmd
    - references.qmd

bibliography: references.bib

# The list-table filter is installed by running this in the terminal:
# quarto add pandoc-ext/list-table

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-title: "On this page"
    toc-depth: 2
    fig-cap-location: margin
    tbl-cap-location: top
    self-contained-math: true
    embed-resources: true
    css: styles.css
    df-print: paged
    code-fold: true
    fontsize: 1em
    tbl-colwidths: [25, 25, 50]
    page-layout: full
    filters:
      - list-table
  pdf:
    documentclass: scrreprt
    include-in-header: custom.sty
    tbl-colwidths: [20, 20, 30, 30]
    filters:
      - list-table

editor: source
