# Introduction {#introduction}

This document describes how the DAVICU-1 database is converted to the OMOP Common
Data Model (CDM) version 5.4.1 and describes the definition of the ETL that will
be used in the implementation. The ETL developed by the INCEPT data team, residing at Department of Intensive Care 4131, Copenhagen University Hospital - Rigshospitalet (called RH4131) in close collaboration with edenceHealth, to serve as a blueprint for and stepping stone toward a national data platform that hosts a Danish Virtual ICU (DAVICU) to enable real-world evidence generation.

DAVICU-1 is the first iteration and contains data from 10 intensive care units (ICUs) from two Danish regions (Capital Region and Region of Southern Denmark).

## Document History {#document-history}

::: list-table
-
    -   Version
    -   Date
    -   Changes
-
    -   0.1
    -   2023-12-14
    -   Internal document used at the mapping workshop
-
    -   0.2
    -   2023-12-28
    -   Updated with notes from mapping workshop
-
    -   0.3
    -   2024-01-12
    -   Updated with notes from infrastructure workshop. And misc. additional
        details. Rename source tables to reflect final pre-processing.
-
    -   0.4
    -   2024-01-24
    -   Finalise infrastructure section, clarification of remaining questions,
        technical instructions for the STEM table, removal of resolved threads
-
    -   0.5
    -   2024-01-31
    -   Update of the person and death logic
-
    -   0.6
    -   2024-02-02
    -   Final edits
-
    -   1.0
    -   2024-02-05
    -   Signed-off structural mapping doc; instructions for v1.0 ETL
-
    -   2.0
    -   2024-08-22
    -   Adaptations to reflect final ETL and converting the document to a stand-alone e-book
:::
