# Overview {#data-mapping}

The definition of OMOP data mapping can usually be performed using the Rabbit-In-A-Hat tool that starts with a profile of the database made by the White Rabbit tool, which however could not run on the cloud node. edenceHealth provided a format for the scan reports and RH4131 crafted bespoke scripts to mimic the behaviour and output of White Rabbit. edenceHealth were then able to create White Rabbit-style scan reports based on the provided scan reports. @sec-appendix-source-tables contains all source tables and fields that have been profiled.

RH4131 provided Parquet files for a subset of sites. Each Parquet file contained data and/or information about one of the following five tables:

-   prescriptions
-   administrations
-   diagnoses_procedures
-   observations (in reality contained in multiple files, named `observations-*.parquet`)
-   course_metadata [^mapping_overview-1]
-   t_person[^mapping_overview-2]

Initially, RH4131 provided three data-source scan report-like files for each site:

-   `database_scan`: the number of rows for each table
-   `table_scan`: information about the columns contained within each table, including data type, uniqueness, missing, etc.
-   `field_scan`: the data for each column within each table

Therefore, the data files had a somewhat nested nature. `database_scan` and `table_scan` contain information usually seen in the first two sheets of a scan report. `field_scan` contains the data usually seen in the following sheets (one per table) of a field scan; however, here it's all contained in one table, `field_scan`.

In addition, RH4131 provided three auxiliary files with care-site metadata, a helper file for undertaking semantic mapping of the drug data, and a mapping file between course_id's and person identifiers.

The exact columns included in each file are listed in @sec-appendix-source-tables.

[^mapping_overview-1]: Visits are called courses in the source data, from the Danish term *forløb*

[^mapping_overview-2]: From the Danish Civil Registration System and holds data such as date of birth and sex [@cpr-regi]
