# Technical Infrastructure   {#technical-infrastructure}

The data live and the ETL run on a secure HPC cloud hosted at the National Genome Center in Denmark and without internet access. Resources can be uploaded if packaged in a Singularity image file. The compute node available for this project has a 40-core 2.1GHz CPU, 192GB RAM, 1.9TB warm storage (XFS drive, NVMe SSD; approx. 1.5TB available).

The ETL is containerised with Docker. The Docker image is hosted on the [GitHub Container Registry](https://ghcr.io) (openly available with `FROM ghcr.io/inceptdk/omop_etl:<tag>`). Instead of Docker, we use Singularity to (i) conform with the HPC nature of the cloud that precludes root access, (ii) prevent version conflicts of software, and (iii) facilitate potential change of cloud system in the future. Singularity image files, derived from Docker images, are brought onto the cloud through a semi-automated process.

The teck stack, thus, consists of Docker/Singularity, Python, SQLAlchemy and DuckDB. DuckDB was preferred over PostgreSQL because it's optimised for OLAP workloads, runs in-process, parallellises extremely well, and is stored everything in a single file with simple handling of read/write permissions.
