# Clinical Data Tables {#clinical-data-tables}

## Table name: PERSON {#table-name-person}

### Reading from t_person and {#reading-from-t_person-and}

NOTE: course_id is visit reference - unique within department only. It's possible that there will be duplicate course_ids across different departments.

+:----------------------------+:-------------------+:---------------------------------------+:------------------------------------------------------------------------------------------------+
| **Destination Field**       | **Source Field**   | **Logic**                              | **Comment**                                                                                     |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| **person_id**               | cpr_enc            | Autgenerate integer                    | Create a record for each distinct patient_id found.                                             |
|                             |                    |                                        |                                                                                                 |
|                             |                    |                                        | In next steps use course_id_cpr_mapping file to find row in t_person corresponding to course_id |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| gender \_concept_id         | c_kon              | K \~ 8532\                             |                                                                                                 |
|                             |                    | M \~ 8507\                             |                                                                                                 |
|                             |                    | else drop person                       |                                                                                                 |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| year \_of_birth             | t_person.d_foddato | Extract year                           |                                                                                                 |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| month_of_birth              | t_person.d_foddato | Extract month                          |                                                                                                 |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| day_of_birth                | t_person.d_foddato | Extract day                            |                                                                                                 |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| birth_datetime              | t_person.d_foddato |                                        | Set time to 00:00:00                                                                            |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| race \_concept_id           |                    | Map to 0                               |                                                                                                 |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| ethnicity_concept_id        |                    | Map to 0                               |                                                                                                 |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| location_id                 |                    |                                        | NULL                                                                                            |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| provider_id                 |                    |                                        | NULL                                                                                            |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| care_site_id                |                    |                                        | NULL                                                                                            |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| person \_source_value       | cpr_enc            | \<column_name\> \|\<column_value\>     |                                                                                                 |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| gender \_source_value       | c_kon              | then \<column_name\>\|\<column_value\> |                                                                                                 |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| gender_source_concept_id    |                    |                                        | NULL                                                                                            |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| race \_source_value         |                    |                                        | NULL                                                                                            |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| race_source_concept_id      |                    |                                        | NULL                                                                                            |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| ethnicity \_source_value    |                    |                                        | NULL                                                                                            |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+
| ethnicity_source_concept_id |                    |                                        | NULL                                                                                            |
+-----------------------------+--------------------+----------------------------------------+-------------------------------------------------------------------------------------------------+

## Table name: DEATH {#table-name-death}

### Reading from t_person {#reading-from-t_person}

+:------------------------+:-------------------+:---------------------------------------------------------------------------------------------------------------------------------------+:-------------------+
| **Destination Field**   | **Source Field**   | **Logic**                                                                                                                              | **Comment**        |
+-------------------------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------+--------------------+
| person_id               | v_pid              | Only for t_person.c_status = 90\                                                                                                       |                    |
|                         |                    | Look up the person_id in the person table by matching the v_pid (\<column_name\>\|\<column_value\> format) and the person_source_value |                    |
+-------------------------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------+--------------------+
| death_date              | d_status_hen_start | When c_status = 90                                                                                                                     | Format: YYYY-MM-DD |
+-------------------------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------+--------------------+
| death_datetime          |                    |                                                                                                                                        | NULL               |
+-------------------------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------+--------------------+
| death_type_concept_id   |                    | 32879 *Registry*                                                                                                                       |                    |
+-------------------------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------+--------------------+
| cause_concept_id        |                    |                                                                                                                                        | NULL               |
+-------------------------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------+--------------------+
| cause_source_value      |                    |                                                                                                                                        | NULL               |
+-------------------------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------+--------------------+
| cause_source_concept_id |                    |                                                                                                                                        | NULL               |
+-------------------------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------+--------------------+

## Table name: VISIT_OCCURENCE {#table-name-visit_occurence}

### Reading from course_metadata, environment variable (SHAK_code) and SHAK code lookup file {#reading-from-course_metadata-environment-variable-shak_code-and-shak-code-lookup-file}

NOTE: Certain variables are nested within course_metadata. The ETL will need to filter the value column to find data related to admin or disc for example

+:------------------------------+:-----------------------------------------+:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+:--------+
| **Destination Field**         | **Source Field**                         | **Logic**                                                                                                                                                                                                                                                                                                                                                                       | Comment |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| **visit\_ occurrence_id**     |                                          | Autogenerated integer                                                                                                                                                                                                                                                                                                                                                           |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| **person_id**                 | course_id                                | Using course_id from course_metadata [having at least ('admdate' or 'admdatetime']{.underline} [- if both they have to match, else don't create a record) and ('dischdate' or ' dischdt']{.underline} [- if both they have to match, else don't create a record)]{.underline} for the row and joining that on the course_id_cpr_mapping file, find the corresponding patient_id |         |
|                               |                                          |                                                                                                                                                                                                                                                                                                                                                                                 |         |
|                               |                                          | Use this patient_id (\<column_name\>\|\<column_value\> format) to join on the PERSON table with the person_source_value to find the person_id                                                                                                                                                                                                                                   |         |
|                               |                                          |                                                                                                                                                                                                                                                                                                                                                                                 |         |
|                               |                                          | Use the person_id                                                                                                                                                                                                                                                                                                                                                               |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| visit_concept_id              | department_type (SHAK code look up file) | First join the SHAK_codes (environment variable and the SHAK code look up file) then look up the department_type in the concept_look up file by joining on the source_code field and the department_type and filtering on 'visit', use the corresponding standard_concept_id                                                                                                    |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| visit_start_date              | value                                    | When variable = 'admdate' use corresponding value. [If not use admdatetime cast into date.]{.underline}                                                                                                                                                                                                                                                                         |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| visit_start_datetime          | value                                    | When variable = 'admdatetime' use corresponding value. [If not use admdate with 00:00:00]{.underline}                                                                                                                                                                                                                                                                           |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| visit_end_date                | value                                    | When variable = 'dischdate' use corresponding value. [f not use 'dischdt' cast into date]{.underline}                                                                                                                                                                                                                                                                           |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| visit_end_datetime            | value                                    | When variable = 'dischdtuse' corresponding value. If not use \`dischdate\` with 00:00:00                                                                                                                                                                                                                                                                                        |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| visit_type_concept_id         |                                          | 32817 *EHR*                                                                                                                                                                                                                                                                                                                                                                     |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| provider_id                   |                                          |                                                                                                                                                                                                                                                                                                                                                                                 | NULL    |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| care_site_id                  | SHAK_code (environment variable)         | Join with the CARE_SITE table using the care_s ite_source_value and the SHAK_code (\<column_name\>\|\<column_value\> format) to find the corresponding care_site_id                                                                                                                                                                                                             |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| visit_source_value            | course_id                                | \<column_name\>\|\<column_value\>                                                                                                                                                                                                                                                                                                                                               |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| visit_source_concept_id       |                                          |                                                                                                                                                                                                                                                                                                                                                                                 | NULL    |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| admitted_from_concept_id      | key = 'transfromid'                      | If key = 'transfromid' and value IS NOT NULL then look up value in CONCEPT_LOOKUP                                                                                                                                                                                                                                                                                               |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| admitted_fr om_source_value   | Value where key = ' transfromid'         | Use 'transfromid\|\<value\>'                                                                                                                                                                                                                                                                                                                                                    |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| discharged_to_concept_id      |                                          | If key = 'chkouttoid' then look up value in CONCEPT_LOOKUP                                                                                                                                                                                                                                                                                                                      |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| discharged\_ to_source_value  | Value where key = 'chkouttoid'           | Use 'chkouttoid\|\<value\>'                                                                                                                                                                                                                                                                                                                                                     |         |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| preceding_visit_occurrence_id |                                          |                                                                                                                                                                                                                                                                                                                                                                                 | NULL    |
+-------------------------------+------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+

## Table name: VISIT_DETAIL {#table-name-visit_detail}

Not in scope.

## Table name: STEM {#table-name-stem}



## Table name: CONDITION_OCCURRENCE {#table-name-condition_occurrence}

### Reading from STEM (filtered on domain_id = 'Condition') {#reading-from-stem-filtered-on-domain_id-condition}

$$video_recording.mp4$$: Part 3 - 00:01:00

+:----------------------------------:+:--------------------:+:-------------------------------------------------------------------:+:-----------:+
| **Destination Field**              | **Source Field**     | **Logic**                                                           | **Comment** |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| \*\*condit ion \_occurrence_id\*\* | Stem_id              |                                                                     |             |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| **person_id**                      | Person_id            |                                                                     |             |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| **con dit ion_concept_id**         | Concept_id           | Read concept_id from stem where !=0 or not NULL                     |             |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| **con dit ion_start_date**         | Start_date           |                                                                     |             |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| condi tio n_start_datetime         | St art_datetime      |                                                                     |             |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| **c ond ition_end_date**           | End_date             | Coales ce(end_date, start_date)                                     |             |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| con dit ion_end_datetime           | End_datetime         | If end date, than caste end date as timestamp, else st art_datetime |             |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| **conditio n_t ype_concept_id**    |                      | 32817 $$EHR$$                                                       |             |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| stop_reason                        |                      |                                                                     | NULL        |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| provider_id                        |                      |                                                                     | NULL        |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| vis it_occurrence_id               | Visit_o ccurrence_id |                                                                     |             |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| visit_detail_id                    |                      |                                                                     | NULL        |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| con dit ion_source_value           | Source_value         |                                                                     |             |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| conditio n_s ource_concept_id      | Sourc e_concept_id   |                                                                     |             |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
| condition\_ sta tus_source_value   |                      |                                                                     | NULL        |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+
|                                    |                      |                                                                     | NULL        |
+------------------------------------+----------------------+---------------------------------------------------------------------+-------------+

## Table name: PROCEDURE_OCCURRENCE {#table-name-procedure_occurrence}

### Reading from STEM (filtered on domain_id = 'Procedure') {#reading-from-stem-filtered-on-domain_id-procedure}

$$video_recording.mp4$$: Part 3 - 00:01:00

+:----------------------------------:+:------------------------:+:-------------:+:-----------:+
| **Destination Field**              | **Source Field**         | **Logic**     | **Comment** |
+------------------------------------+--------------------------+---------------+-------------+
| \*\*proced ure \_occurrence_id\*\* | Stem_id                  |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| **person_id**                      | Person_id                |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| **pro ced ure_concept_id**         | Concept_id               |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| **procedure_date**                 | Start_date               |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| pr ocedure_datetime                | S t art_datetime         |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| pr ocedure_end_date                | End_date                 |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| pro ced ure_end_datetime           | End_datetime             |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| **procedur e_t ype_concept_id**    |                          | 32817 $$EHR$$ |             |
+------------------------------------+--------------------------+---------------+-------------+
| mod ifier_concept_id               | Modifi e r_concept_id    |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| quantity                           | Quantity                 |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| provider_id                        |                          |               | NULL        |
+------------------------------------+--------------------------+---------------+-------------+
| vis it_occurrence_id               | Visit\_ o ccurrence_id   |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| visit_detail_id                    |                          |               | NULL        |
+------------------------------------+--------------------------+---------------+-------------+
| pro ced ure_source_value           | Source_value             |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| procedur e_s ource_concept_id      | Sour c e_concept_id      |               |             |
+------------------------------------+--------------------------+---------------+-------------+
| mo dif ier_source_value            | Modifier \_ source_value |               |             |
+------------------------------------+--------------------------+---------------+-------------+

## Table name: DEVICE_EXPOSURE {#table-name-device_exposure}

### Reading from STEM (filtered on domain_id = 'Device') {#reading-from-stem-filtered-on-domain_id-device}

$$video_recording.mp4$$: Part 3 - 00:01:00

+:---------------------------------:+:--------------------:+:-------------:+:-----------:+
| **Destination Field**             | **Source Field**     | **Logic**     | **Comment** |
+-----------------------------------+----------------------+---------------+-------------+
| -   \*devi ce_exposure_id\*\*     | stem_id              |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| **person_id**                     | person_id            |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| **d evice_concept_id**            | concept_id           |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| **device\_ exp osure_start_date** | start_date           |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| device_ex pos ure_start_datetime  | st art_datetime      |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| dev ice \_exposure_end_date       | end_date             |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| device\_ exp osure_end_datetime   | end_datetime         |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| \*\*dev ice \_type_concept_id\*\* |                      | 32817 $$EHR$$ |             |
+-----------------------------------+----------------------+---------------+-------------+
| unique_device_id                  |                      |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| production_id                     |                      |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| quantity                          |                      |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| provider_id                       |                      |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| v isit_occurrence_id              | visit_o ccurrence_id |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| visit_detail_id                   |                      |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| d evice_source_value              | source_value         |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| dev ice \_source_concept_id       | sourc e_concept_id   |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| unit_concept_id                   | uni t_concept_id     |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| unit_source_value                 | unit\_ source_value  |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| u nit \_source_concept_id         |                      |               |             |
+-----------------------------------+----------------------+---------------+-------------+

## Table name: MEASUREMENT {#table-name-measurement}

### Reading from STEM (filtered on domain_id = 'Measurement') {#reading-from-stem-filtered-on-domain_id-measurement}

$$video_recording.mp4$$: Part 3 - 00:01:00

+:--------------------------------------:+:--------------------:+:-------------:+:-----------:+
| **Destination Field**                  | **Source Field**     | **Logic**     | **Comment** |
+----------------------------------------+----------------------+---------------+-------------+
| **measurement_id**                     | stem_id              |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| **person_id**                          | person_id            |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| **mea sur ement_concept_id**           | concept_id           |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| **measurement_date**                   | start_date           |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| me asurement_datetime                  | st art_datetime      |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| measurement_time                       |                      |               | NULL        |
+----------------------------------------+----------------------+---------------+-------------+
| \*\*measurem ent \_type_concept_id\*\* |                      | 32817 $$EHR$$ |             |
+----------------------------------------+----------------------+---------------+-------------+
| o perator_concept_id                   | operato r_concept_id |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| value_as_number                        | val ue_as_number     |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| v alue_as_concept_id                   | value_a s_concept_id |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| unit_concept_id                        | uni t_concept_id     |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| range_low                              | Range_low            |               | NULL        |
+----------------------------------------+----------------------+---------------+-------------+
| range_high                             | Range_high           |               | NULL        |
+----------------------------------------+----------------------+---------------+-------------+
| provider_id                            |                      |               | NULL        |
+----------------------------------------+----------------------+---------------+-------------+
| v isit_occurrence_id                   | visit_o ccurrence_id |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| visit_detail_id                        |                      |               | NULL        |
+----------------------------------------+----------------------+---------------+-------------+
| mea sur ement_source_value             | source_value         |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| measurem ent \_source_concept_id       | sourc e_concept_id   |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| unit_source_value                      | unit\_ source_value  |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| u nit \_source_concept_id              |                      |               | NULL        |
+----------------------------------------+----------------------+---------------+-------------+
| value_source_value                     | val ue_as_number     |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| me asurement_event_id                  |                      |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| meas_e ven t_field_concept_id          |                      |               |             |
+----------------------------------------+----------------------+---------------+-------------+

## Table name: SPECIMEN

## Table name: OBSERVATION {#table-name-observation}

### Reading from STEM (filtered on domain_id = 'Observation') {#reading-from-stem-filtered-on-domain_id-observation}

$$video_recording.mp4$$: Part 3 - 00:01:00

+:--------------------------------------:+:--------------------:+:-------------:+:-----------:+
| **Destination Field**                  | **Source Field**     | **Logic**     | **Comment** |
+----------------------------------------+----------------------+---------------+-------------+
| **observation_id**                     | stem_id              |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| **person_id**                          | person_id            |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| **obs erv ation_concept_id**           | concept_id           |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| **observation_date**                   | start_date           |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| ob servation_datetime                  | st art_datetime      |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| \*\*observat ion \_type_concept_id\*\* |                      | 32817 $$EHR$$ |             |
+----------------------------------------+----------------------+---------------+-------------+
| value_as_number                        | val ue_as_number     |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| value_as_string                        | val ue_as_string     |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| v alue_as_concept_id                   | value_a s_concept_id |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| qu alifier_concept_id                  |                      |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| unit_concept_id                        | uni t_concept_id     |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| provider_id                            |                      |               | NULL        |
+----------------------------------------+----------------------+---------------+-------------+
| v isit_occurrence_id                   | visit_o ccurrence_id |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| visit_detail_id                        |                      |               | NULL        |
+----------------------------------------+----------------------+---------------+-------------+
| obs erv ation_source_value             | source_value         |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| observat ion \_source_concept_id       | sourc e_concept_id   |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| unit_source_value                      | unit\_ source_value  |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| q ual ifier_source_value               |                      |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| value_source_value                     | value\_ source_value |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| ob servation_event_id                  |                      |               |             |
+----------------------------------------+----------------------+---------------+-------------+
| obs_e ven t_field_concept_id           |                      |               |             |
+----------------------------------------+----------------------+---------------+-------------+

## Table name: DRUG_EXPOSURE {#table-name-drug_exposure}

### Reading from STEM (filtered on domain_id = 'Drug') {#reading-from-stem-filtered-on-domain_id-drug}

$$video_recording.mp4$$: Part 3 - 00:49:00

+:---------------------------------:+:--------------------:+:-------------:+:-----------:+
| **Destination Field**             | **Source Field**     | **Logic**     | **Comment** |
+-----------------------------------+----------------------+---------------+-------------+
| **d rug_exposure_id**             | Stem_id              |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| **person_id**                     | Person_id            |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| **drug_concept_id**               | Concept_id           |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| **drug_e xpo sure_start_date**    | Start_date           |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| drug_exp osu re_start_datetime    | St art_datetime      |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| \*\*drug \_expo sure_end_date\*\* | End_date             |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| drug_e xpo sure_end_datetime      | End_datetime         |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| verbatim_end_date                 |                      |               | NULL        |
+-----------------------------------+----------------------+---------------+-------------+
| **dr ug\_ type_concept_id**       |                      | 32817 $$EHR$$ |             |
+-----------------------------------+----------------------+---------------+-------------+
| stop_reason                       |                      |               | NULL        |
+-----------------------------------+----------------------+---------------+-------------+
| refills                           |                      |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| quantity                          | Quantity             |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| days_supply                       |                      |               | NULL        |
+-----------------------------------+----------------------+---------------+-------------+
| sig                               |                      |               | NULL        |
+-----------------------------------+----------------------+---------------+-------------+
| route_concept_id                  | Rout e_concept_id    |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| lot_number                        |                      |               | NULL        |
+-----------------------------------+----------------------+---------------+-------------+
| provider_id                       |                      |               | NULL        |
+-----------------------------------+----------------------+---------------+-------------+
| vi sit_occurrence_id              | Visit_o ccurrence_id |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| visit_detail_id                   |                      |               | NULL        |
+-----------------------------------+----------------------+---------------+-------------+
| drug_source_value                 | Source_value         |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| dr ug\_ source_concept_id         | Sourc e_concept_id   |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| r oute_source_value               | Route\_ source_value |               |             |
+-----------------------------------+----------------------+---------------+-------------+
| do se\_ unit_source_value         |                      |               |             |
+-----------------------------------+----------------------+---------------+-------------+

## Table name: OBSERVATION_PERIOD {#table-name-observation_period}

### Reading from clinical tables (including visit_occ) {#reading-from-clinical-tables-including-visit_occ}

NOTE: min/max dates all established from dates across all filled in clinical tables

$$video_recording.mp4$$: [Part 3 - 00:01:00]{.underline}

+:------------------------------------:+:----------------:+:------------------------------------------------------:+:-----------:+
| **Destination Field**                | **Source Field** | **Logic**                                              | **Comment** |
+--------------------------------------+------------------+--------------------------------------------------------+-------------+
| **obse rvation_period_id**           |                  | Au togenerated integer                                 |             |
+--------------------------------------+------------------+--------------------------------------------------------+-------------+
| **person_id**                        |                  | CREATE observation period for each person_id in PERSON |             |
+--------------------------------------+------------------+--------------------------------------------------------+-------------+
| **observat ion\_ period_start_date** |                  | MIN(EVENT $$START$$ DATES)                             |             |
+--------------------------------------+------------------+--------------------------------------------------------+-------------+
| **observ atio n_period_end_date**    |                  | MAX(EVENT $$END$$ DATES)                               |             |
+--------------------------------------+------------------+--------------------------------------------------------+-------------+
| **p erio d_type_concept_id**         |                  | 32817 $$EHR$$                                          |             |
+--------------------------------------+------------------+--------------------------------------------------------+-------------+
