# Standardised Derived Elements {#standardised-derived-elements}

## T able name: DRUG_ERA {#t-able-name-drug_era}

A Drug Era is defined as a span of time when the Person is assumed to be
exposed to a particular active ingredient. A Drug Era is not the same as
a Drug Exposure: Exposures are individual records corresponding to the
source when Drug was delivered to the Person, while successive periods
of Drug Exposures are combined under certain rules to produce continuous
Drug Eras.

Generated as part of ETL process using [standard OHDSI SQL
script](https://ohdsi.github.io/CommonDataModel/sqlScripts.html#Drug_Eras).

## T able name: DOSE_ERA {#t-able-name-dose_era}

A Dose Era is defined as a span of time when the Person is assumed to be
exposed to a constant dose of a specific active ingredient.

Generated as part of ETL process using [standard OHDSI SQL
script](https://github.com/OHDSI/MIMIC/blob/df97a75cd974c491e595c8b007a79f7326066cb1/etl/etl/cdm_dose_era.sql).

## T able name: CONDITION_ERA {#t-able-name-condition_era}

A Condition Era is defined as a span of time when the Person is assumed
to have a given condition. Condition Eras are chronological periods of
Condition Occurrences.

Generated as part of ETL process using [standard OHDSI SQL
script](https://ohdsi.github.io/CommonDataModel/sqlScripts.html#Condition_Eras).
