name: Linting

"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the code
        uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - name: set up python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'  # caching pip dependencies
          python-version: '3.12'

      - name: Install dependencies
        run: |
          set -eux
          pip install -r requirements.txt -r requirements.dev.txt

      # https://github.com/pre-commit/action
      - name: run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch
