# Nota bene: This workflow file must also exist in identical form in the docs branch for publishing to the gh-pages branch to function proper

on:
  workflow_dispatch:
  push:
    branches: docs

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout content branch
        uses: actions/checkout@v3
        with:
          ref: docs

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install TinyTeX and list-table extension
        run: |
          quarto install tinytex
          quarto add pandoc-ext/list-table --no-prompt

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
