name: Pytest

"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - name: set up python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'  # caching pip dependencies
          python-version: '3.12'

      - name: Install dependencies
        run: |
          set -eux
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements.dev.txt

      - name: Test with pytest
        run: |
          export PYTHONPATH=$PWD
          export ETL_RUN_INTEGRATION_TESTS=ON
          pytest tests/testsuite.py -v

      - name: Coverage with pytest
        run: |
          export PYTHONPATH=$PWD
          coverage run --omit=tests -m unittest
          coverage html

      - uses: actions/upload-artifact@v3
        with:
          name: codecov-report
          path: htmlcov
